services:
  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: ${USER}-${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}-nginx
    restart: always
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - ${NGINX_PROJECT_PORT}:80
    volumes:
      - ./conf/nginx:/etc/nginx
      - ./www:/usr/share/nginx/html
      - ./conf/scripts:/opt/scripts
    networks:
      - project_network
    logging:
      options:
        max-size: "30m"
        max-file: "5"

  mariadb:
    image: mariadb:${DB_VERSION:-latest}
    container_name: ${USER}-${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}-mariadb
    restart: always
    volumes:
      - ./database_deploy/:/docker-entrypoint-initdb.d/:ro
      - ./database:/var/lib/mysql
      - ./conf/mariadb:/etc/mysql
    networks:
      - project_network
    ports:
      - ${MYSQL_DATABASE_PORT}:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Jwx77aGCr2I7w}
      MYSQL_DATABASE: ${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}_db
      MYSQL_USER: ${MYSQL_USER:-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-jjj}
    logging:
      options:
        max-size: "30m"
        max-file: "5"

  php-kernel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_MODULES: ${PHP_MODULES}
        USER_ID: ${USER_ID}
    image: ${PHP_VERSION}_${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}-kernel
    container_name: ${USER}-${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}-php
    restart: always
    expose:
      - "9000"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/scripts:/opt/scripts
    networks:
      - project_network
    env_file:
      - .env.docker
      - .env
    depends_on:
      - nginx
      - mariadb
    logging:
      options:
        max-size: "30m"
        max-file: "5"

networks:
  project_network:
    name: ${USER}-${PROJECT_CUSTOM_NAME:-$PROJECT_NAME}_network
